#!/bin/csh

if ( -f ~/.cshrc.override ) then
  source $HOME/.cshrc.override
  exit(0)
endif

#exit if non interactive
if ( ! $?prompt ) exit
if ( ! $?term ) exit


# [[ ":$PATH:" != *":/path/to/add:"* ]] && PATH="/path/to/add:${PATH}"
set path = ( $path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin)



if( -d ~/.config/cshrc.d && -r  ~/.config/cshrc.d && -x  ~/.config/cshrc.d ) then
  foreach file (~/.config/cshrc.d/*.csh)
    if (-f "$file" && -r "$file") then
      source "$file"
    endif
  end
endif

if( -d ~/.cshrc.local.d && -r  ~/.cshrc.local.d && -x  ~/.cshrc.local.d ) then
  foreach file (~/.cshrc.local.d/*.csh)
    if (-f "$file" && -r "$file") then
      source "$file"
    endif
  end
endif

if ( -f ~/.cshrc.local && -r ~/.cshrc.local ) then
    source $HOME/.cshrc.local
endif
