#!/bin/csh

#exit if non interactive
if ( ! $?prompt ) exit
if ( ! $?term ) exit


if( -d ~/.config/cshrc.d && -r  ~/.config/cshrc.d && -x  ~/.config/cshrc.d ) then
  foreach file (~/.config/cshrc.d/*.csh)
    if (-f "$file" && -r "$file") then
      source "$file"
    endif
  end
endif

if ( -f ~/.cshrc.local && -r ~/.cshrc.local ) then
    source $HOME/.cshrc.local
endif
