#!/usr/bin/env python

import os,sys

def get_install_map():
  ignored_files = ("install","uninstall",".git")
  install_map =  { }

  standard_files = (file for file in os.listdir(".") if file not in ignored_files and file not in install_map)

  for item in standard_files:
    if os.path.isdir(item):
      install_map[item] = "~/.config"
    else:
      install_map[item] = "~/"

  return install_map

def run_install():
  install_map = get_install_map()
  for src,dst in install_map.items():
    src_path  = os.path.abspath(os.path.expanduser(src))
    dest_path = os.path.expanduser(os.path.join(dst,src))
    print("Installing %s to %s"%(src_path,dest_path))
    os.symlink(src_path,dest_path)

def run_uninstall():
  install_map = get_install_map()
  for src,dst in install_map.items():
    dest_path = os.path.expanduser(os.path.join(dst,src))
    print("Removing %s"%dest_path)
    os.unlink(dest_path)



if __name__=="__main__":
  print(sys.argv[0])
  if os.path.basename(sys.argv[0]) =="install":
    run_install()
  else:
    run_uninstall()
