#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091

# This file is loaded when opening a non login shell

if [ -f ~/.bashrc.override ]; then
  source ~/.bashrc.override
  exit 0
fi

if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi


# exit if not interactive
[[ $- != *i* ]] && return




if [[ -d ~/.config/bashrc.d && -r ~/.config/bashrc.d && -x ~/.config/bashrc.d ]]; then
  for file in ~/.config/bashrc.d/*.sh; do
     [[ -f "${file}" && -r "${file}" ]] && source "${file}"
  done
fi

pathmunge  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin after
cleanpath

# Source local Configs
if [[ -d ~/.bashrc.local.d && -r ~/.bashrc.local.d && -x ~/.bashrc.local.d ]]; then
  for file in ~/.bashrc.local.d/*.sh; do
     [[ -f "${file}" && -r "${file}" ]] && source "${file}"
  done
fi

if [[ -f ~/.bashrc.local ]]; then
  source ~/.bashrc.local
fi
