#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091
# This file is loaded when opening a non login shell


# exit if not interactive
[[ $- != *i* ]] && return


if [[ -d ~/.config/bashrc.d && -r ~/.config/bashrc.d && -x ~/.config/bashrc.d ]]; then
  for file in ~/.config/bashrc.d/*.sh; do
     [[ -f "${file}" && -r "${file}" ]] && source "${file}"
  done
fi

# Source local configs
if [[ -f ~/.bashrc.local ]]; then
  source ~/.bashrc.local
fi
