#! /usr/bin/env bash
# shellcheck disable=SC1090,SC1091

#This file is run anytime you log in to the system (ie via ssh, or vnc)
if [ -f ~/.profile.local ]; then
  . ~/.profile.local
fi

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi